FROM node:23-alpine AS build

WORKDIR /app

COPY wasm-app/package*.json ./
RUN npm install

COPY wasm-app/. .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
